### PR TITLE
Attempt to fix up the links for the requirements.

### PR DESCRIPTION
**Pull request by pillows**
I know there are some problems...especially on canvas.txt with factlib.
I tried to be as consistent as possible with the links.

### CODE REVIEW

**Comment by pillows** [comment]
People might get a hiccup with the unicode and setuptools error.
Fixes here:

as3:/usr/local/lib/python2.7/site-packages# cat sitecustomize.py
import sys  
reload(sys)  
sys.setdefaultencoding('utf8')

(Shameless copy+paste: http://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte)

Setuptools:
wget https://pypi.python.org/packages/source/s/setuptools/setuptools-18.5.zip#md5=db877c1ea889a036e26321db71105a14
unzip setuptools-18.5.zip
cd setuptools-18.5
sudo python ez_setup.py

I must be doing something wrong. Jumping through so many loops to get the requirements installed.

**Comment by TimothyFitz** [comment]
You're not doing anything wrong. Those docs were written for setting up new sandboxes while the company existed, so they're not public open-source quality, they've bitrotted and we're the Canvas AWS account has been closed so parts will never work again.

We should make that clearer; there's one sentence in the preamble but it's easy to miss.

**Comment by TimothyFitz** [comment]
I don't think we should go from s3 urls to pypi urls. We should be changing to standard requirements.txt style: 
distribute==0.6.19
django-indexer==0.3.0

Internally we went with s3 urls because we found installing from our s3 buckets to be much more reliable than installing from pypi, but that ONLY mattered for cloud instance creation. Local dev was never an issue.

**Comment by pillows** [comment]
You know what, you're right. I completely forgot about doing this in the normal requirement format.

But also what about the weird packages that are in some of the files. Like canvas.txt for example. There was a factlib package. Is that a custom package or open source? (I did not find a download for that.)

**Comment by TimothyFitz** [comment]
Yeah that's a tiny custom package. It's in deploy/factlib. Just a couple C functions to speed up some weird text decoding. It's actually not needed anywhere in the running codebase, so it's fine to remove that line.

Edit: btw, we're in the middle of getting permissions sorted out to accept pull requests. If you update to the standard style I'll go ahead and merge this PR when I can.

**Comment by pillows** [comment]
There is another PR to replace this one. I felt that removing the requirement txt files was optional but if needed you can remove it.

**Pull request closed without merging**
